version: '3.7'

volumes:
    jenkins-docker-certs:

services:
  jenkins:
    build:
        context: .
        dockerfile: LifeUp.Dockerfile
        args:
            buildno: 1

    restart: unless-stopped

    networks:
        - jenkins
    ports:
        - 8048:8080
        #- 50000:50000
        #- 2376:2376

    privileged: true

    environment:
        #- DOCKER_HOST=tcp://docker:2376
        - DOCKER_CERT_PATH=/certs/client
        - DOCKER_TLS_VERIFY=1

    volumes:
        # config jenkins data
        - ./jenkins-data:/var/jenkins_home
        # mount docker sock and binary for docker in docker
        - /var/run/docker.sock:/var/run/docker.sock
        - /usr/bin/docker:/usr/bin/docker
        # certificates jenkins
        - jenkins-docker-certs:/certs/client:ro

    container_name: jenkins-docker

networks: 
    jenkins:
        #TODO: add name

